travis:
  secure:
    BINSTAR_TOKEN: hg7CUMHP3rbfbSfILg+obLWkTXLO451dDspMQGaPYHKiPot1gi3qykQZi54QBTlhMT6L5P5JRfgGA7k3GZETm0asMwq8joy7f7hbh4hNif3EbJw7MbacEi/h0H2Yw2rSKQMdM9rwS0h5LrXK8HejI6GjBBvIK/zcLqTqCX2cPfYSFyU/CVqHt0q6S1QILZkVUWKl6Iqx15/AJhdQ3Ff+nYvp7LWhLTywpis1hI8xuaiLK3Gkb9qtyfbz/hlQ6okBPc6Pbalc61ehCBliPi/3X8qg5SbTs61VFA6g/bzrScRiPN/6jY8zt4fNk6fPD/+KtvDYjiSQv3ogHMYUI02aoh94M6MAME8rjoHStW+70UleydpKrKWtnzmWx3mx4PmNFQf1E7ymDDGD6jCMh8bDwKR+eC0FfDrVF20uFOvUpwYfyBzKA0zK2TqGHBsK+gmFAjLrke/9Z2p4eByawOI/jGEnHZxAlsdu8N6QyJJkjERLPrlbfDNHC+zzLLzbDLAERWXcfbyTvBJfRGyLFeJOmFBDvDjJzjtylXmCvFr4k7GpIPthS6Sr5giVw9frnaiAzdAdUydD8+UENT3tFcf11cJM8vaK9hEvpYVZmGiUCTJ/lQl+ZG2vtFlgs88V7HUXkqRC/yeM9lcPIIdDMLfv70wVrB/TNKYSCFh6w6cKzKE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
